# Example Config to demonstrate configuration options
---
global:
  port: ${PORT}
  refresh_interval: ${REFRESH_INTERVAL}
  cloud_controller_url: ${CLOUD_CONTROLLER_URL}
apps:
  enabled: true
  resources:
    - name: my-cool-app
    - name: optional-app-example
      optional: true
    - name: app-with-route
      routes:
        - app-hostname.app.cloudfoundry
    - name: optional-app-with-routes
      optional: true
      routes:
        - hostname1.first.domain
        - hostname2.first.domain
        - hostname3.second.domain
spaces:
  enabled: true
  resources:
    - name: dev
      allow_ssh: true
    - name: test
      allow_ssh: true
    - name: prod
      allow_ssh: false
