---
apps:
  - name: alertmanager
  - name: cf-metrics
  - name: consul-0
  - name: consul-1
  - name: consul-2
  - name: cortex
  - name: elasticsearch-metrics
  - name: es-proxy
  - name: grafana
  - name: kibana
  - name: kong
  - name: prometheus
  - name: redis-metrics
  - name: sk-analytics
  - name: sk-api
  - name: sk-challenge
  - name: sk-credential
  - name: sk-dbconfigs
  - name: sk-devicepolicy
  - name: sk-esconfigs
  - name: sk-events
  - name: sk-ews
  - name: sk-fido
  - name: sk-flow
  - name: sk-functions
  - name: sk-http
  - name: sk-iovation
  - name: sk-jumio
  - name: sk-lexisnexis
  - name: sk-manifest
  - name: sk-mfacontainer
  - name: sk-node
  - name: sk-oe
  - name: sk-openid
  - name: sk-portal
  - name: sk-sdk
  - name: sk-totp
  - name: sk-transunion
  - name: sk-userpolicy
  - name: sk-variables
  - name: sk-webhook
  - name: usps
